apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ryumem.fullname" . }}
  labels:
    {{- include "ryumem.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.googleApiKey }}
  GOOGLE_API_KEY: {{ .Values.secrets.googleApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.adminApiKey }}
  ADMIN_API_KEY: {{ .Values.secrets.adminApiKey | quote }}
  {{- end }}
